#ifndef RUNTIME_SCENE_BRIDGE_CONTRACT_WRITEBACK_SUITE_H
#define RUNTIME_SCENE_BRIDGE_CONTRACT_WRITEBACK_SUITE_H

#include <stdbool.h>

bool test_runtime_scene_bridge_writeback_overlay_preserves_non_physics_state(void);
bool test_runtime_scene_bridge_writeback_rejects_foreign_extension_namespace(void);
bool test_runtime_scene_bridge_writeback_rejects_forbidden_top_level_overlay_key(void);
bool test_runtime_scene_bridge_writeback_rejects_invalid_space_mode_value(void);
bool test_runtime_scene_bridge_writeback_rejects_non_object_physics_extension_payload(void);
bool test_runtime_scene_bridge_writeback_rejects_missing_overlay_meta(void);
bool test_runtime_scene_bridge_writeback_rejects_stale_logical_clock(void);
bool test_runtime_scene_bridge_writeback_rejects_wrong_overlay_producer(void);
bool test_runtime_scene_bridge_writeback_rejects_negative_logical_clock(void);
bool test_runtime_scene_bridge_writeback_rejects_runtime_core_unit_system_overlay(void);
bool test_runtime_scene_bridge_writeback_rejects_runtime_core_world_scale_overlay(void);
bool test_runtime_scene_bridge_writeback_space_mode_tiebreak_rejects_lexically_larger_producer(void);
bool test_runtime_scene_bridge_writeback_space_mode_tiebreak_accepts_newer_clock(void);

#endif
