"""Same-functional attribution using calibrated cubic projection and archived native fields."""
import json,hashlib
from pathlib import Path
from assess_cfd_obstacle3d_pressure_attribution import native_trace
R=Path(__file__).resolve().parents[1];D=R/'build/c3d-cubic-pressure-attribution'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def run():
 out=D/'assessment.json';assert not out.exists();matrix_path=R/'build/c3d-obstacle/agent-evidence/qualification.json';matrix=json.loads(matrix_path.read_text());worker=matrix['worker_sha256'];assert worker==sha(R/'build/cfd-optimized/physics_sim_session_worker')=='c2a234ff0238f12b64c739ccbb1f6304e2ff3244613b125eb453fd40d08caf64'
 projection_audit=R/'build/c3d-cubic-pressure-projection/checkpoint-audit.json';audit=json.loads(projection_audit.read_text());records=[]
 for n in (16,32):
  entry=next(x for x in audit['observations'] if x['n']==n);pr=Path(entry['receipt']);assert sha(pr)==entry['receipt_sha256'];receipt=json.loads(pr.read_text());projection_path=Path(receipt['command'][receipt['command'].index('--output')+1]);assert sha(projection_path)==receipt['artifact_sha256'][str(projection_path)];projection=json.loads(projection_path.read_text());reference_receipt=Path(projection['input_receipt']);assert sha(reference_receipt)==projection['input_receipt_sha256'];rr=json.loads(reference_receipt.read_text());ref=json.loads(Path(rr['command'][rr['command'].index('--output')+1]).read_text())
  row=next(x for x in matrix['records'] if x['case']==f'n{n}');binary=Path(matrix['evidence_root'])/f'n{n}.bin';assert sha(binary)==row['binary_sha256'];status=row['status'];provenance=row['result']['provenance'];assert provenance['worker_sha256']==worker and provenance['channel']['dimensions_m']==[4,2,2] and provenance['channel']['center_x_m']==2 and provenance['channel']['volume_flow_m3_s']==ref['flow_m3_s']==.008 and provenance['fluid']['dynamic_viscosity_pa_s']==ref['mu']==.1
  assert status['geometry']==[dict(kind='stationary_aligned_cube',min_m=[1.5,.5,.5],max_m=[2.5,1.5,1.5])] and provenance['grid']==[2*n,n,n] and status['solve_mode']=='steady_obstacle_duct';trace=native_trace(binary,2.);native_force=status['boundary_force_budget']['body_pressure_force_n'][0];assert abs(trace['force_n']-native_force)<1e-12
  raw=projection['raw_reference_pressure_force_n'];projected=projection['native_trace_on_reference_n'];reconstruction=projected-raw;field=native_force-projected;total=native_force-raw;assert abs(reconstruction+field-total)<1e-15
  records.append(dict(n=n,reference_pressure_force_n=raw,reference_projected_native_trace_n=projected,archived_native_pressure_force_n=native_force,reconstruction_error_n=reconstruction,field_functional_error_n=field,total_functional_error_n=total,reconstruction_error_relative=reconstruction/raw,field_functional_error_relative=field/raw,total_functional_error_relative=total/raw,native_binary=str(binary),native_binary_sha256=sha(binary),native_slab_averages_pa=trace['slab_averages_pa'],projection_receipt_sha256=sha(pr),input_reference_receipt_sha256=sha(reference_receipt),complete_pressure_field_error_norm_measured=False))
 result=dict(schema='physics_sim_c3d_cubic_pressure_attribution_v1',worker_sha256=worker,archived_native_fields=True,native_qualification_sha256=sha(matrix_path),projection_audit_sha256=sha(projection_audit),records=records,physical_accuracy_certified=False,persistent_goal_complete=False,scope='signed additive pressure-force functional decomposition using matched archived native fields and the calibrated cubic reference projection; current reference raw/reaction equilibrium still above1%; not a complete pressure-field norm or new native run')
 out.write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result,indent=2))
if __name__=='__main__':run()
